### ISSUE TITLE
Failed to install on Darwin Kernel Version 18.5.0

### ISSUE THREAD

**Issue by vulogov** [cyclone-scheme/homebrew-cyclone#8]
`╰─λ brew install cyclone-scheme/cyclone/cyclone                                       1 < 16:48:18
==> Installing cyclone from cyclone-scheme/cyclone
==> Downloading https://github.com/justinethier/cyclone/archive/v0.11.2.tar.gz
Already downloaded: /Users/vulogov/Library/Caches/Homebrew/downloads/e037b2f4ea8a5ed7b6b3ae324b18777f9b004f89889de0e175b647dd44e9d8b1--cyclone-0.11.2.tar.gz
==> make
Last 15 lines from /Users/vulogov/Library/Logs/Homebrew/cyclone/01.make:
cyclone -A . libs/cyclone/match.sld
cyclone -A . libs/cyclone/test.sld
Error: Unable to open file: "/usr/local/share/cyclone/cyclone/test.scm"
Call history:
scheme/base.sld:foldl
scheme/base.sld:foldr
scheme/base.sld:foldl
scheme/base.sld:foldr
scheme/base.sld:foldl
scheme/base.sld:Cyc-for-each-loop-1
scheme/cyclone/libraries.sld:lib:check-system-path
cyclone.scm:read-file
scheme/file.sld:call-with-input-file

make: *** [libs/cyclone/test.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/cyclone-scheme/homebrew-cyclone/issues`

**Comment by adamfeuer** [comment]
@vulogov It fails for me too the same way on Darwin Kernel 18.6.0. I'll look into it.

**Comment by justinethier** [comment]
@vulogov @adamfeuer Sorry about that - the following libraries were relocated in 0.11.2:

- (scheme cyclone test) was moved to (cyclone test) 
- (scheme cyclone match) was moved to (cyclone match) 

Both of these libraries are now under `libs/cyclone` in the source tree.

Also, the following new library was added:

- `(cyclone concurrent)`

**Comment by vulogov** [comment]
Did you pushed the updates ? Brew downloads same v0.11.2.tar.gz and throw same error

**Comment by adamfeuer** [comment]
@justinethier No problem, I saw it when I started looking into the breakage. I have a fix in the works, testing it now.

@vulogov I'm working on a fix, will let you know when I have it pushed.

**Comment by adamfeuer** [comment]
@vulogov @justinethier Ok, pushed and merged a fix, and tested it on my Mac... it works.

@vulogov Will you try it out and see if it works for you? Just follow the usual installation instructions.

**Comment by vulogov** [comment]
Thank you @adamfeuer !
